swagger: "2.0"
info:
  description: "Swagger for Budget App"
  version: "1.0.0"
  title: "Budget App"
tags:
  - name: "Income"
    description: "Income"
  - name: "Group"
    description: "Group"
  - name: "user"
    description: "user"
schemes:
  - "http"
paths:
  /user/login:
    get:
      tags:
        - "user"
      summary: "Logs user into the system"
      description: ""
      operationId: "loginUser"
      produces:
        - "application/json"
      parameters:
        - name: "username"
          in: "query"
          description: "The user name for login"
          required: true
          type: "string"
        - name: "password"
          in: "query"
          description: "The password for login in clear text"
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
          headers:
            X-Rate-Limit:
              type: "integer"
              format: "int32"
              description: "calls per hour allowed by the user"
            X-Expires-After:
              type: "string"
              format: "date-time"
              description: "date in UTC when token expires"
        "400":
          description: "Invalid username/password supplied"
  /user/logout:
    get:
      tags:
        - "user"
      summary: "Logs out current logged in user session"
      description: ""
      operationId: "logoutUser"
      produces:
        - "application/json"
      parameters: []
      responses:
        default:
          description: "successful operation"
  /user:
    post:
      tags:
        - "user"
      summary: "Create user"
      description: "This can only be done by the logged in user."
      operationId: "createUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Created user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        default:
          description: "successful operation"
    get:
      tags:
        - "user"
      summary: "Get all users"
      description: ""
      operationId: "getUsers"
      produces:
        - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: array
            items:
              $ref: "#/definitions/User"
  /user/{username}:
    get:
      tags:
        - "user"
      summary: "Get user by user name"
      description: ""
      operationId: "getUserByName"
      produces:
        - "application/json"
      parameters:
        - name: "username"
          in: "path"
          description: "The name that needs to be fetched. Use user1 for testing. "
          required: true
          type: "string"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
    put:
      tags:
        - "user"
      summary: "Updated user"
      description: "This can only be done by the logged in user."
      operationId: "updateUser"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "username"
          in: "path"
          description: "name that need to be updated"
          required: true
          type: "string"
        - in: "body"
          name: "body"
          description: "Updated user object"
          required: true
          schema:
            $ref: "#/definitions/User"
      responses:
        "400":
          description: "Invalid user supplied"
        "404":
          description: "User not found"
    delete:
      tags:
        - "user"
      summary: "Delete user"
      description: "This can only be done by the logged in user."
      operationId: "deleteUser"
      produces:
        - "application/json"
      parameters:
        - name: "username"
          in: "path"
          description: "The name that needs to be deleted"
          required: true
          type: "string"
      responses:
        "400":
          description: "Invalid username supplied"
        "404":
          description: "User not found"
  /group:
    post:
      tags:
        - "Group"
      summary: "Add a new group"
      description: ""
      operationId: "addGroup"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Group object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Group"
      responses:
        "201":
          description: "Created"
          schema:
            $ref: "#/definitions/Group"
        "405":
          description: "Invalid input"
          schema:
            $ref: '#/definitions/ModelApiResponse'
    put:
      tags:
        - "Group"
      summary: "Update group"
      description: ""
      operationId: "updateGroup"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Group object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Group"
      responses:
        "200":
          description: "Updated"
          schema:
            $ref: "#/definitions/Group"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
    get:
      tags:
        - "Group"
      summary: "Get all Group"
      description: ""
      operationId: "getAllGroup"
      produces:
        - "application/json"
      responses:
        "200":
          description: "All Group"
          schema:
            type: array
            items:
              $ref: "#/definitions/Group"
  /group/{groupId}:
    get:
      tags:
        - "Group"
      summary: "Find group by ID"
      description: "Returns a single group"
      operationId: "getGroupById"
      produces:
        - "application/json"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group to return"
          required: true
          type: "string"
          format: "uuid"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Group"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Group not found"
    delete:
      tags:
        - "Group"
      summary: "Delete group by ID"
      description: "Deletes a single group"
      operationId: "deleteGroupById"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group to delete"
          required: true
          type: "string"
          format: "uuid"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Group not found"
  /group/{groupId}/income:
    post:
      tags:
        - "Income"
      summary: "Add a new income"
      description: ""
      operationId: "addIncome"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Income object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Income"
      responses:
        "201" :
          description: "Created"
          schema:
            $ref: "#/definitions/Income"
        "405":
          description: "Invalid input"
          schema:
            $ref: '#/definitions/ModelApiResponse'
    put:
      tags:
        - "Income"
      summary: "Update income"
      description: ""
      operationId: "updateIncome"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group"
          required: true
          type: "string"
          format: "uuid"
        - in: "body"
          name: "body"
          description: "Income object that needs to be added"
          required: true
          schema:
            $ref: "#/definitions/Income"
      responses:
        "200":
          description: "Updated"
          schema:
            $ref: "#/definitions/Income"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Pet not found"
        "405":
          description: "Validation exception"
    get:
      tags:
        - "Income"
      summary: "Get all Income"
      description: ""
      operationId: "getAllIncome"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group"
          required: true
          type: "string"
          format: "uuid"
      produces:
        - "application/json"
      responses:
        "200":
          description: "All Income"
          schema:
            type: array
            items:
              $ref: "#/definitions/Income"
  /group/{groupId}/income/{incomeId}:
    get:
      tags:
        - "Income"
      summary: "Find income by ID"
      description: "Returns a single income"
      operationId: "getIncomeById"
      produces:
        - "application/json"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group"
          required: true
          type: "string"
          format: "uuid"
        - name: "incomeId"
          in: "path"
          description: "ID of income to return"
          required: true
          type: "string"
          format: "uuid"
      responses:
        "200":
          description: "Successful operation"
          schema:
            $ref: "#/definitions/Income"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Income not found"
    delete:
      tags:
        - "Income"
      summary: "Delete income by ID"
      description: "Deletes a single income"
      operationId: "deleteIncomeById"
      parameters:
        - name: "groupId"
          in: "path"
          description: "ID of group"
          required: true
          type: "string"
          format: "uuid"
        - name: "incomeId"
          in: "path"
          description: "ID of income to delete"
          required: true
          type: "string"
          format: "uuid"
      responses:
        "200":
          description: "Successful operation"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Income not found"
definitions:
  Income:
    type: "object"
    required:
      - "amount"
      - "description"
      - "type"
    properties:
      id:
        type: "string"
        format: "uuid"
      amount:
        type: "integer"
        format: "int64"
      description:
        type: "string"
      type:
        type: string
        enum: &IncomeType
          - INCOME
          - EXPENSE
    xml:
      name: "Income"
  Group:
    type: "object"
    required:
      - "name"
      - "description"
    properties:
      id:
        type: "string"
        format: "uuid"
      name:
        type: "string"
      description:
        type: "string"
      budget:
        type: "integer"
        format: "int64"
      incomeList:
        type: array
        items:
          $ref: "#/definitions/Income"
    xml:
      name: "Group"
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      username:
        type: "string"
      firstName:
        type: "string"
      lastName:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
      phone:
        type: "string"
      userStatus:
        type: "integer"
        format: "int32"
        description: "User Status"
      roles:
        type: array
        items:
          type: "string"
    xml:
      name: "User"
  ModelApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Budget App"
  url: "http://github.com"